apiVersion: v1
kind: Pod
metadata:
  name: testpod
  namespace: default
spec:
  containers:
    - name: test-container
      image: busybox
      command: ["sh", "-c", "echo Hello Kubernetes && sleep 3600"]
